#!/bin/bash

# x_dims=(4 8)
# h_dims=(4 8)
lrs=(0.01 0.02 0.03)
optims=(adam sgd)
bszs=(32)

embed_dims=(256)
num_layers=(6)
num_heads=(4)
key_sizes=(64)

echo 'Submitting SBATCH jobs...'


# for lr in ${lrs[@]}
# do
#   for bsz in ${bszs[@]}
#   do
#     for embed_dim in ${embed_dims[@]}
#     do
#       for layers in ${num_layers[@]}
#       do
#         for heads in ${num_heads[@]}
#         do
#           for key_size in ${key_sizes[@]}
#           do
#             for optim in ${optims[@]}
#             do
#               echo "#!/bin/bash" >> temprun.sh
#               echo "#SBATCH --partition=long"  >> temprun.sh
#               echo "#SBATCH --cpus-per-task=2" >> temprun.sh
#               echo "#SBATCH --gres=gpu:1" >> temprun.sh
#               echo "#SBATCH --mem=16G" >> temprun.sh
#               echo "#SBATCH --time=7:59:00 " >>  temprun.sh
#               echo "#SBATCH -o /home/mila/c/cristian-dragos.manta/projects/partial-cliques/slurm-%j.out" >> temprun.sh

#               echo "module load cuda/11.1/cudnn/8.1" >> temprun.sh
#               echo "source /home/mila/c/cristian-dragos.manta/anaconda3/bin/activate" >> temprun.sh
#               echo "conda activate dag-gfn" >> temprun.sh
#               echo "export PYTHONPATH=${PYTHONPATH}:/home/mila/c/cristian-dragos.manta/projects/partial-cliques" >> temprun.sh

#               echo "python train.py --optimizer ${optim} --embed_dim ${embed_dim} --num_heads ${heads} --num_layers ${layers} --key_size ${key_size} --num_eval_samples 10 --prefill 500 --num_iterations 5000 --batch_size ${bsz} --num_samples 100 --x_dim 8 --h_dim 4 --K 2 --seed 0 --log_every 10 --lr ${lr}" >> temprun.sh

#               eval "sbatch temprun.sh"
#               rm temprun.sh
#             done
#           done
#         done
#       done
#     done
#   done
# done

# 6 latents
echo "#!/bin/bash" >> temprun.sh
echo "#SBATCH --partition=long"  >> temprun.sh
echo "#SBATCH --cpus-per-task=2" >> temprun.sh
echo "#SBATCH --gres=gpu:48gb:1" >> temprun.sh
echo "#SBATCH --mem=48G" >> temprun.sh
echo "#SBATCH --time=9:59:00 " >>  temprun.sh
echo "#SBATCH -o /home/mila/c/cristian-dragos.manta/projects/partial-cliques/slurm-%j.out" >> temprun.sh

echo "module load cuda/11.1/cudnn/8.1" >> temprun.sh
echo "source /home/mila/c/cristian-dragos.manta/anaconda3/bin/activate" >> temprun.sh
echo "conda activate dag-gfn" >> temprun.sh
echo "export PYTHONPATH=${PYTHONPATH}:/home/mila/c/cristian-dragos.manta/projects/partial-cliques" >> temprun.sh

echo "python train.py --max_traj_length 5 --latent_structure random_chain_graph_c3 --pb uniform --optimizer sgd --embed_dim 256 --num_heads 4 --num_layers 6 --key_size 64 --num_eval_samples 10 --prefill 500 --num_iterations 5000 --batch_size 32 --num_samples 100 --x_dim 3 --h_dim 6 --K 2 --seed 0 --log_every 10 --lr 0.03" >> temprun.sh

eval "sbatch temprun.sh"
rm temprun.sh

# 9 latents
echo "#!/bin/bash" >> temprun.sh
echo "#SBATCH --partition=long"  >> temprun.sh
echo "#SBATCH --cpus-per-task=2" >> temprun.sh
echo "#SBATCH --gres=gpu:48gb:1" >> temprun.sh
echo "#SBATCH --mem=48G" >> temprun.sh
echo "#SBATCH --time=9:59:00 " >>  temprun.sh
echo "#SBATCH -o /home/mila/c/cristian-dragos.manta/projects/partial-cliques/slurm-%j.out" >> temprun.sh

echo "module load cuda/11.1/cudnn/8.1" >> temprun.sh
echo "source /home/mila/c/cristian-dragos.manta/anaconda3/bin/activate" >> temprun.sh
echo "conda activate dag-gfn" >> temprun.sh
echo "export PYTHONPATH=${PYTHONPATH}:/home/mila/c/cristian-dragos.manta/projects/partial-cliques" >> temprun.sh

echo "python train.py --max_traj_length 8 --latent_structure random_chain_graph_c3 --pb uniform --optimizer sgd --embed_dim 256 --num_heads 4 --num_layers 6 --key_size 64 --num_eval_samples 10 --prefill 500 --num_iterations 5000 --batch_size 32 --num_samples 100 --x_dim 5 --h_dim 9 --K 2 --seed 0 --log_every 10 --lr 0.03" >> temprun.sh

eval "sbatch temprun.sh"
rm temprun.sh

# 12 latents
echo "#!/bin/bash" >> temprun.sh
echo "#SBATCH --partition=long"  >> temprun.sh
echo "#SBATCH --cpus-per-task=2" >> temprun.sh
echo "#SBATCH --gres=gpu:48gb:1" >> temprun.sh
echo "#SBATCH --mem=48G" >> temprun.sh
echo "#SBATCH --time=9:59:00 " >>  temprun.sh
echo "#SBATCH -o /home/mila/c/cristian-dragos.manta/projects/partial-cliques/slurm-%j.out" >> temprun.sh

echo "module load cuda/11.1/cudnn/8.1" >> temprun.sh
echo "source /home/mila/c/cristian-dragos.manta/anaconda3/bin/activate" >> temprun.sh
echo "conda activate dag-gfn" >> temprun.sh
echo "export PYTHONPATH=${PYTHONPATH}:/home/mila/c/cristian-dragos.manta/projects/partial-cliques" >> temprun.sh

echo "python train.py --max_traj_length 11 --latent_structure random_chain_graph_c3 --pb uniform --optimizer sgd --embed_dim 256 --num_heads 4 --num_layers 6 --key_size 64 --num_eval_samples 10 --prefill 500 --num_iterations 5000 --batch_size 32 --num_samples 100 --x_dim 7 --h_dim 12 --K 2 --seed 0 --log_every 10 --lr 0.03" >> temprun.sh

eval "sbatch temprun.sh"
rm temprun.sh

# 15 latents -> OOM
# echo "#!/bin/bash" >> temprun.sh
# echo "#SBATCH --partition=long"  >> temprun.sh
# echo "#SBATCH --cpus-per-task=2" >> temprun.sh
# echo "#SBATCH --gres=gpu:48gb:1" >> temprun.sh
# echo "#SBATCH --mem=64G" >> temprun.sh
# echo "#SBATCH --time=9:59:00 " >>  temprun.sh
# echo "#SBATCH -o /home/mila/c/cristian-dragos.manta/projects/partial-cliques/slurm-%j.out" >> temprun.sh

# echo "module load cuda/11.1/cudnn/8.1" >> temprun.sh
# echo "source /home/mila/c/cristian-dragos.manta/anaconda3/bin/activate" >> temprun.sh
# echo "conda activate dag-gfn" >> temprun.sh
# echo "export PYTHONPATH=${PYTHONPATH}:/home/mila/c/cristian-dragos.manta/projects/partial-cliques" >> temprun.sh

# echo "python train.py --max_traj_length 14 --latent_structure random_chain_graph_c3 --pb uniform --optimizer sgd --embed_dim 256 --num_heads 4 --num_layers 6 --key_size 64 --num_eval_samples 10 --prefill 500 --num_iterations 5000 --batch_size 32 --num_samples 100 --x_dim 9 --h_dim 15 --K 2 --seed 0 --log_every 10 --lr 0.03" >> temprun.sh

# eval "sbatch temprun.sh"
# rm temprun.sh